import { StyleSheet ,Dimensions} from "react-native";
const Styles = StyleSheet.create({
    InputBoxBody:{
        backgroundColor:"white",
        width:"100%",
        padding:10,
        height:50,
        marginBottom:10,
        justifyContent:"center",
        flexDirection:"row",
        zIndex:100000,
    },
    InputBox:{
        paddingLeft:15,
        justifyContent:"center",
        width:"70%",
        height:30,
        marginRight:5,
        top:0,
    },
    InputBoxSelected:{
        paddingLeft:15,
        justifyContent:"center",
        width:"70%",
        height:30,
        marginRight:5,
        top:0,
        borderBottomColor:"#15d441",
        borderBottomWidth:1
    },
    InputBoxBodyButtonDiv:{
        width:"25%",
        height:25,
        backgroundColor:"#1e35a7",
        top:2.5,
        paddingTop:2,
        paddingBottom:2,
        alignItems:"center"
    },
    InputBoxBodyButton:{
        padding:5,
        fontSize:12,
        color:"white"
    },
    statusOfInput:{
        top:7,
        width:"6%",
    },
    DropdownHeader:{
        height:"100%",
        fontSize:20,
        backgroundColor:"transparent",
        top:5
    },
    DropdownBody:{
        position:"absolute",
        width:"100%",
        backgroundColor:"#999",
        borderBottomLeftRadius:5,
        borderBottomRightRadius:5,
        top:40,
        overflow:"scroll",
    },
    DropdownBodyItem:{
        fontSize:18,
        marginLeft:2,
        marginRight:2,
        marginBottom:2,
        padding:8,
        backgroundColor:"white",
    }
});
export default Styles;